import turtle as t
import math as np

t.shape('turtle')
S = open('inp.txt', 'r')
A = S.readlines()
S.close()
for i in range(0, 6):
    A[i] = int(A[i])
    if A[i] == 0:
        t.forward(20)
        t.left(90)
        t.forward(40)
        t.left(90)
        t.forward(40)
        t.left(90)
        t.penup()
        t.forward(30)
        t.pendown()
    elif A[i] == 1:
        t.penup()
        t.forward(20)
        t.pendown()
        t.left(90)
        t.forward(40)
        t.left(135)
        t.forward(20 * np.sqrt(2))
        t.penup()
        t.left(45)
        t.forward(20)
        t.left(90)
        t.forward(30)
        t.pendown()
    elif A[i] == 2:
        t.left(45)
        t.forward(20 * np.sqrt(2))
        t.left(45)
        t.forward(20)
        t.left(90)
        t.forward(20)
        t.penup()
        t.left(90)
        t.forward(40)
        t.left(90)
        t.pendown()
        t.forward(20)
        t.penup()
        t.forward(10)
        t.pendown()
    elif A[i] == 3:
        t.left(45)
        t.forward(20 * np.sqrt(2))
        t.left(135)
        t.forward(20)
        t.right(135)
        t.forward(20 * np.sqrt(2))
        t.left(135)
        t.forward(20)
        t.penup()
        t.left(90)
        t.forward(40)
        t.left(90)
        t.forward(30)
        t.pendown()
    elif A[i] == 4:
        t.penup()
        t.left(90)
        t.forward(40)
        t.left(180)
        t.pendown()
        t.forward(20)
        t.left(90)
        t.forward(20)
        t.left(90)
        t.forward(20)
        t.left(180)
        t.forward(40)
        t.penup()
        t.left(90)
        t.forward(10)
        t.pendown()
    elif A[i] == 5:
        t.forward(20)
        t.left(90)
        t.forward(20)
        t.left(90)
        t.forward(20)
        t.right(90)
        t.forward(20)
        t.right(90)
        t.forward(20)
        t.right(90)
        t.penup()
        t.forward(40)
        t.left(90)
        t.forward(10)
        t.pendown()
    elif A[i] == 6:
        t.left(90)
        t.forward(20)
        t.right(45)
        t.forward(20 * np.sqrt(2))
        t.back(20 * np.sqrt(2))
        t.right(45)
        t.forward(20)
        t.right(90)
        t.forward(20)
        t.right(90)
        t.forward(20)
        t.left(180)
        t.penup()
        t.forward(30)
        t.pendown()
    elif A[i] == 7:
        t.left(90)
        t.forward(20)
        t.right(45)
        t.forward(20 * np.sqrt(2))
        t.left(135)
        t.forward(20)
        t.penup()
        t.left(90)
        t.forward(40)
        t.left(90)
        t.forward(30)
        t.pendown()
    elif A[i] == 8:
        t.forward(20)
        t.left(90)
        t.forward(40)
        t.left(90)
        t.forward(20)
        t.left(90)
        t.forward(20)
        t.left(90)
        t.forward(20)
        t.back(20)
        t.right(90)
        t.forward(20)
        t.left(90)
        t.penup()
        t.forward(30)
        t.pendown()
    elif A[i] == 9:
        t.left(45)
        t.forward(20 * np.sqrt(2))
        t.left(45)
        t.forward(20)
        t.left(90)
        t.forward(20)
        t.left(90)
        t.forward(20)
        t.left(90)
        t.forward(20)
        t.right(90)
        t.penup()
        t.forward(20)
        t.left(90)
        t.forward(10)
        t.pendown()
